c_stdlib_version:   # [osx and x86_64]
  - '11.0'          # [osx and x86_64]

blas_impl:
  - mkl        # [(linux and not aarch64) or win]
  - openblas   # [linux and aarch64]
  - accelerate # [osx]

# Support for Tegra architecture (Jetson Orin)
arm_variant_type:  # [linux and aarch64]
  - sbsa           # [linux and aarch64]
  - tegra          # [linux and aarch64]
