MACOSX_DEPLOYMENT_TARGET:   # [osx and x86_64]
- '11.0'                    # [osx and x86_64]

blas_impl:
  - mkl        # [(linux and not aarch64) or win]
  - openblas   # [linux and aarch64]
  - accelerate # [osx]
